"""add jobs table

Revision ID: 2b6d5b713152
Revises: 1c7e3cb14c25
Create Date: 2026-06-11 16:29:53.249436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b6d5b713152'
down_revision: Union[str, Sequence[str], None] = '1c7e3cb14c25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'FAILED', 'SUCCESS', name='celerystatuses'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.String(), nullable=True),
    sa.Column('stderr', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
