"""add uuid

Revision ID: 70724e6a965f
Revises: 1a31c24d01b7
Create Date: 2026-06-15 17:20:35.556007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70724e6a965f'
down_revision: Union[str, Sequence[str], None] = '1a31c24d01b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('uuid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'uuid')
    # ### end Alembic commands ###
