"""primary uuid, none task id

Revision ID: 8ed11697f9fa
Revises: 70724e6a965f
Create Date: 2026-06-15 19:53:15.513517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed11697f9fa'
down_revision: Union[str, Sequence[str], None] = '70724e6a965f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("jobs_pkey", "jobs", type_="primary")
    op.alter_column("jobs", "task_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("jobs", "uuid", existing_type=sa.VARCHAR(), nullable=False)
    op.create_primary_key("jobs_pkey", "jobs", ["uuid"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("jobs_pkey", "jobs", type_="primary")
    op.alter_column("jobs", "uuid", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("jobs", "task_id", existing_type=sa.VARCHAR(), nullable=False)
    op.create_primary_key("jobs_pkey", "jobs", ["task_id"])
    # ### end Alembic commands ###
