"""add composite index on jobs(user_id, created_at)

Revision ID: b30c8ec8f637
Revises: 68a96284d13c
Create Date: 2026-06-15 20:44:59.152351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b30c8ec8f637'
down_revision: Union[str, Sequence[str], None] = '68a96284d13c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_jobs_user_id_created_at', 'jobs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_user_id_created_at', table_name='jobs')
    # ### end Alembic commands ###
